os: osx

language: go

go:
  - 1.5.1

env:
- GO15VENDOREXPERIMENT=1

before_install:
  - brew update
  - brew install glide
  - glide install

notifications:
  slack: sitbackteam:tb1IP3OwCM1BmTPwyDDqpZIy
