sudo: false

language: go

go:
  - 1.5.1

env:
- GO15VENDOREXPERIMENT=1

before_install:
  - wget "https://github.com/Masterminds/glide/releases/download/0.7.2/glide-0.7.2-linux-amd64.tar.gz" -O /tmp/glide.tar.gz
  - mkdir -p /tmp/glide
  - tar -xvzf /tmp/glide.tar.gz -C /tmp/glide/
  - export PATH=$PATH:/tmp/glide/linux-amd64/
  - go get github.com/mitchellh/gox
  - make bootstrap

notifications:
  slack: sitbackteam:tb1IP3OwCM1BmTPwyDDqpZIy
